language: ruby
rvm:
- 1.9.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - lftp
      - tree
before_install:
- bash _scripts/install.sh
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
